/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Staff(props) {
  const { nodes, materials } = useGLTF("/models/staff-transformed.glb");
  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  });

  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      scale={[3, 3, 3]}
      position={[0, -2, 0]}
    >
      {/* ...original meshes... */}
    </group>
  );
}

useGLTF.preload("/models/staff-transformed.glb");
